### ISSUE TITLE
Visual Studio Code 1.38.1 has updated Extension icon

### ISSUE THREAD

**Issue by nathankc** [awsdocs/aws-toolkit-vs-code-user-guide#2]
VS Code > Activity Bar/ Exetnsions screenshot is out of date - latest VS Code release has updated icons

**Comment by Paul-B-AWS** [comment]
Thank you for your feedback. We are in the process of updating the user guide for the AWS Toolkit for VS Code. These changes should appear in the next few days.

**Comment by Paul-B-AWS** [comment]
The screenshots have been updated. For example, see the [navigation](https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/toolkit-navigation.html) page.
You can also see other updates by viewing the first couple of entries on the [doc history](https://github.com/awsdocs/aws-toolkit-vs-code-user-guide/blob/master/doc_source/doc-history.md) page.
