### ISSUE TITLE
Extension "AWS Toolkit for Visual Studio Code" does not exist

### ISSUE THREAD

**Issue by moltar** [awsdocs/aws-toolkit-vs-code-user-guide#4]
https://github.com/awsdocs/aws-toolkit-vs-code-user-guide/blob/master/doc_source/setup-toolkit.md

> In the search box for Extensions, search for AWS Toolkit for Visual Studio Code. Choose the entry to see its details in the right pane.

The name of the extension is "AWS Toolkit"

If you search for "AWS Toolkit for Visual Studio Code", it actually produces zero results.

Worst yet, someone can hijack that name and a rogue extension would be found.

Best yet is to just link to the extension directly.

Or if you don't want to link to the extension store, just link to the github repo: https://github.com/aws/aws-toolkit-vscode

**Comment by moltar** [comment]
I see there is already a PR #3 with a similar complaint.

**Comment by awsdan** [comment]
Thanks!
