### ISSUE TITLE
Missing documentation on how to use toolkit with Systems Manager

### ISSUE THREAD

**Issue by ghost** [awsdocs/aws-toolkit-vs-code-user-guide#9]
Missing documentation on how to use toolkit with Systems Manager

https://github.com/awsdocs/aws-toolkit-vs-code-user-guide/blob/370fcd81569c599e637937d9cd4901cd16607614/doc_source/working-with-aws.md?plain=1#L9

**Comment by justinmk3** [comment]
Thanks for the note. There is a section under "AWS Explorer": https://docs.aws.amazon.com/toolkit-for-vscode/latest/userguide/systems-manager-automation-docs.html

does that cover what you're looking for?

(We are considering re-arranging the topics so that they are easier to find.)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
